version: 2

# Settings common to each job.
job_defaults: &job_defaults
  docker:
  - image: circleci/node:10.5.0-browsers
  working_directory: ~/repo

# Install NPM dependencies.
run_npm_install: &run_npm_install
  run:
    name: Install NPM Dependencies
    command: npm install

# Restore versioned cache.
restore_versioned_cache: &restore_versioned_cache
  restore_cache:
    keys:
    - $CACHE_VERSION-dependencies-{{ checksum "package-lock.json" }}
      # Fallback to using the latest cache if no exact match is found.
    - $CACHE_VERSION-dependencies-

jobs:
  code_coverage:
    <<: *job_defaults
    steps:
    - checkout
    - *restore_versioned_cache
    - *run_npm_install
    - run:
        name: Run Code Coverage
        command: npm run test -- --code-coverage --progress=false --watch=false
    - run:
        name: Upload Code Coverage to Codecov
        command: npm run codecov -- --token=$CODECOV_TOKEN

  deploy_prod:
    <<: *job_defaults
    steps:
    - checkout
    - *restore_versioned_cache
    - run:
        name: Install Firebase NPM Dependencies
        command: npm --prefix functions install
    - run:
        name: Build Artifacts
        command: |
          npm run build -- --prod
          npm run ng -- run $PROJECT_NAME:server:production
          cp -a functions/dist/browser/. functions/dist/public/
          mv functions/dist/public/index.html functions/dist/public/index-public.html
    - deploy:
        name: Deploy to Firebase
        command: npm run firebase -- deploy --token=$FIREBASE_TOKEN --non-interactive

  unit_tests:
    <<: *job_defaults
    steps:
    - checkout
    - *restore_versioned_cache
    - *run_npm_install
    - run:
        name: Run Unit Tests
        command: npm run test -- --progress=false --watch=false

  update_cache:
    <<: *job_defaults
    steps:
    - checkout
    - *restore_versioned_cache
    - *run_npm_install
    - save_cache:
        key: $CACHE_VERSION-dependencies-{{ checksum "package-lock.json" }}
        paths:
        - node_modules

workflows:
  version: 2
  test_build_deploy:
    jobs:
    - update_cache
    - unit_tests:
        requires:
        - update_cache
    - code_coverage:
        requires:
        - update_cache
    - deploy_prod:
        requires:
        - unit_tests
        filters:
          branches:
            only: master
